#!/usr/bin/env python

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

L = [1,2,3]
s = 0

while L[2] < 4_000_000:
    L[2] = L[1] + L[0]
    L[0],L[1] = L[1],L[2]
    if L[0]%2 == 0:
        s += L[0]

print(s)
