#!/usr/bin/env python

# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle 	  	Tₙ=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
# Pentagonal 	  	Pₙ=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
# Hexagonal 	  	Hₙ=n(2n−1) 	  	1, 6, 15, 28, 45, ...

# It can be verified that T₂₈₅ = P₁₆₅ = H₁₄₃ = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

tri = [0]
penta = [0]
hexa = [0]

both = []

while len(both) < 3:
    hexa.append(len(hexa) * (len(hexa) * 2 - 1))
    while penta[-1] < hexa[-1]:
        penta.append(len(penta) * (len(penta) * 3 - 1) / 2)
    while tri[-1] < hexa[-1]:
        tri.append(len(tri) * (len(tri)+1) / 2)
    if tri[-1] == hexa[-1] and penta[-1] == hexa[-1]:
        both.append(hexa[-1])

print(both)
